# Generated by Django 5.1.7 on 2025-03-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, height_field='img_height', upload_to='profile_img/', width_field='img_width'),
        ),
    ]
